export type Role='owner'|'manager'|'viewer';
export type BusinessType='Restaurant'|'Hardware'|'Services';
export type Customer={id:string;name:string;email:string;status:'Active'|'Lead';value:number};
export type Item={id:string;name:string;category:string;stock:number;price:number;status:'In stock'|'Low stock'|'Out'};
export type Activity={id:string;message:string;date:string};
export type Business={id:string;name:string;type:BusinessType;currency:string;customers:Customer[];items:Item[];orders:number;revenue:number;growth:number;activities:Activity[]};
export const businesses:Business[]=[
{id:'blue-table',name:'Blue Table',type:'Restaurant',currency:'COP',orders:184,revenue:48200000,growth:12,customers:[{id:'bt-c1',name:'María Torres',email:'maria@example.com',status:'Active',value:480000},{id:'bt-c2',name:'Julián Díaz',email:'julian@example.com',status:'Active',value:320000},{id:'bt-c3',name:'Laura Gómez',email:'laura@example.com',status:'Lead',value:180000}],items:[{id:'bt-i1',name:'Limonada de coco',category:'Drinks',stock:34,price:18000,status:'In stock'},{id:'bt-i2',name:'Arroz marinero',category:'Main',stock:8,price:42000,status:'Low stock'},{id:'bt-i3',name:'Ceviche clásico',category:'Main',stock:0,price:36000,status:'Out'}],activities:[{id:'bt-a1',message:'Order #1842 completed',date:'Today · 09:42'},{id:'bt-a2',message:'Inventory alert: Arroz marinero',date:'Today · 08:17'}]},
{id:'northline',name:'Northline',type:'Hardware',currency:'COP',orders:96,revenue:31700000,growth:7,customers:[{id:'nl-c1',name:'Construcciones Mar',email:'compras@mar.example',status:'Active',value:920000},{id:'nl-c2',name:'Obras del Caribe',email:'admin@caribe.example',status:'Active',value:610000}],items:[{id:'nl-i1',name:'Cemento 50kg',category:'Materials',stock:42,price:36500,status:'In stock'},{id:'nl-i2',name:'Tubería PVC 1/2"',category:'Plumbing',stock:6,price:12800,status:'Low stock'},{id:'nl-i3',name:'Taladro profesional',category:'Tools',stock:0,price:480000,status:'Out'}],activities:[{id:'nl-a1',message:'Purchase order #087 received',date:'Today · 10:12'},{id:'nl-a2',message:'New customer: Obras del Caribe',date:'Yesterday · 16:20'}]},
{id:'coralworks',name:'CoralWorks',type:'Services',currency:'COP',orders:63,revenue:26400000,growth:18,customers:[{id:'cw-c1',name:'Hotel Bahía',email:'ops@bahia.example',status:'Active',value:1400000},{id:'cw-c2',name:'Studio Norte',email:'hello@studio.example',status:'Lead',value:760000}],items:[{id:'cw-i1',name:'Web platform',category:'Development',stock:3,price:5200000,status:'In stock'},{id:'cw-i2',name:'UX audit',category:'Consulting',stock:5,price:1800000,status:'In stock'},{id:'cw-i3',name:'Support plan',category:'Retainer',stock:1,price:950000,status:'Low stock'}],activities:[{id:'cw-a1',message:'Project milestone approved',date:'Today · 11:05'},{id:'cw-a2',message:'Proposal sent to Studio Norte',date:'Yesterday · 14:32'}]}];