import'./demo-bridge';import styleText from'./style.css?inline';import{createWorkspace,type WorkspaceEvent}from'./application/workspace';import{permissions}from'./application/workspace';import type{Role}from'./core/business';
export type MountOptions={tenantId?:string;role?:Role;onEvent?:(event:WorkspaceEvent)=>void};
export type MountRoot=HTMLElement|ShadowRoot;
const injectStyles=(root:MountRoot)=>{
if(root.querySelector(':scope > style[data-microfrontend-style]'))return;
const style=document.createElement('style');
style.dataset['microfrontendStyle']='';
const shadow=root.getRootNode() instanceof ShadowRoot;
style.textContent=shadow
?styleText.replace(':root{--demo-bg:#f4f5f2;--demo-paper:#fff;--demo-ink:#17201c;--demo-muted:#68736c;--demo-line:#dfe4df;--demo-soft:#edf0ec;--demo-accent:#766f9f;font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:var(--demo-ink);background:var(--demo-bg);line-height:1.45}',':host{--demo-bg:var(--mb-bg,#f4f5f2);--demo-paper:var(--mb-paper,#fff);--demo-ink:var(--mb-ink,#17201c);--demo-muted:var(--mb-muted,#68736c);--demo-line:var(--mb-line,#dfe4df);--demo-soft:var(--mb-soft,#edf0ec);--demo-accent:var(--mb-accent,#766f9f);--demo-font-family:var(--mb-font-family,Inter,ui-sans-serif,system-ui,sans-serif);color:var(--demo-ink);background:var(--demo-bg);font-family:var(--demo-font-family);line-height:1.45}')
:styleText;
root.prepend(style);
};
export function mount(root:MountRoot,options:MountOptions={}){
injectStyles(root);const ws=createWorkspace(options.tenantId,{onEvent:options.onEvent});if(options.role)ws.setRole(options.role);let section='overview',query='',assistant='',demoStep=0;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));const money=(n:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);
function proof(){const b=ws.business,ctx=ws.context;const caps=permissions[ctx.role];if(!demoStep)return '';
 if(demoStep===1)return `<div class="proof-result"><label>STEP 01 · TENANT SWITCH</label><h3>Business context changed</h3><div class="proof-grid"><span>tenantId<b>${b.id}</b></span><span>business<b>${esc(b.name)}</b></span><span>customers<b>${b.customers.length}</b></span><span>revenue<b>${money(b.revenue)} ${b.currency}</b></span></div><p>The same workspace is now reading a different tenant dataset. No page reload.</p></div>`;
 if(demoStep===2)return `<div class="proof-result"><label>STEP 02 · ROLE CHANGE</label><h3>Permissions changed for <em>${ctx.role}</em></h3><div class="capabilities">${['view','create','edit','reports','manage-users'].map(x=>`<span class="${caps.includes(x)?'allowed':'blocked'}">${x} · ${caps.includes(x)?'allowed':'blocked'}</span>`).join('')}</div><p>Try Customers or Inventory now. Viewer can read, but cannot create records.</p></div>`;
 if(demoStep===3)return `<div class="proof-result"><label>STEP 03 · REAL WRITE</label><h3>Write data into <em>${esc(b.name)}</em></h3><form id="proofForm" class="proof-form"><input id="proofName" placeholder="Customer name" required><input id="proofEmail" placeholder="Email" type="email" required><button type="submit" ${ws.can('create')?'':'disabled'}>${ws.can('create')?'Create customer':'Blocked by role'}</button></form><p>Tenant before: <b>${b.customers.length}</b> customers. After submit, the write event will show the new record and tenantId.</p></div>`;
 if(demoStep===4)return `<div class="proof-result"><label>STEP 04 · TENANT-SCOPED ASSISTANT</label><h3>Ask the active workspace</h3><div class="proof-assistant"><input id="proofAsk" value="${esc(assistant||'How many customers does this tenant have?')}" placeholder="Ask about this tenant"><button id="proofAskBtn">Ask</button></div>${assistant?`<div class="answer"><b>${esc(ws.assistant(assistant))}</b><small>source: ${esc(b.id)} · role: ${ctx.role}</small></div>`:''}<p>The assistant receives the active tenant context; it does not search another business.</p></div>`;
 return `<div class="proof-result"><label>STEP 05 · REQUEST TRACE</label><h3>Follow the request boundary</h3><div class="trace-chain"><span>UI / App Shell</span><i>→</i><span>tenantId=<b>${b.id}</b></span><i>→</i><span>Business module</span><i>→</i><span>TenantRepository</span><i>→</i><span>PostgreSQL RLS <small>modeled</small></span></div><div class="event-log">${ws.trace().map(e=>`<div><b>${e.type}</b><span>${esc(e.detail)}</span><small>tenant=${esc(e.tenantId)} · role=${e.role}</small></div>`).join('')}</div></div>`;
}
function render(){const b=ws.business;const customers=ws.customers().filter(c=>(c.name+' '+c.email).toLowerCase().includes(query.toLowerCase()));const items=ws.items().filter(i=>(i.name+' '+i.category).toLowerCase().includes(query.toLowerCase()));const nav=[['overview','Overview'],['customers','Customers'],['catalog',b.type==='Services'?'Services':'Inventory'],['operations',b.type==='Services'?'Projects':'Orders'],['reports','Reports']];
 let page='';
 if(section==='customers')page=`<div class="panel"><div class="toolbar"><div><label>CUSTOMER DIRECTORY</label><h2>Customers</h2></div><input id="search" placeholder="Search name or email" value="${esc(query)}"><button id="addCustomer" ${ws.can('create')?'':'disabled'}>+ Customer</button></div><table><thead><tr><th>Name</th><th>Email</th><th>Status</th><th>Value</th></tr></thead><tbody>${customers.map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.email)}</td><td>${c.status}</td><td>${money(c.value)}</td></tr>`).join('')}</tbody></table></div>`;
 else if(section==='catalog')page=`<div class="panel"><div class="toolbar"><div><label>${b.type.toUpperCase()} CATALOG</label><h2>${b.type==='Services'?'Services & capacity':'Inventory'}</h2></div><input id="search" placeholder="Search catalog" value="${esc(query)}"><button id="addItem" ${ws.can('create')?'':'disabled'}>+ ${b.type==='Services'?'Service':'Item'}</button></div><table><thead><tr><th>Name</th><th>Category</th><th>Stock</th><th>Price</th><th>Status</th></tr></thead><tbody>${items.map(i=>`<tr><td><b>${esc(i.name)}</b></td><td>${esc(i.category)}</td><td>${i.stock}</td><td>${money(i.price)}</td><td>${i.status}</td></tr>`).join('')}</tbody></table></div>`;
 else if(section==='operations')page=`<div class="panel"><label>OPERATIONS</label><h2>${b.type==='Services'?'Active projects':'Recent orders'}</h2><div class="operation-grid"><article><span>In progress</span><b>${Math.round(b.orders*.32)}</b></article><article><span>Completed</span><b>${Math.round(b.orders*.61)}</b></article><article><span>Attention</span><b>${b.items.filter(i=>i.status!=='In stock').length}</b></article></div><div class="activity">${b.activities.map(a=>`<p><b>${esc(a.message)}</b><span>${a.date}</span></p>`).join('')}</div></div>`;
 else if(section==='reports')page=`<div class="panel"><label>REPORTING</label><h2>Tenant performance</h2><div class="report-grid"><article><span>Revenue</span><b>${money(b.revenue)} ${b.currency}</b></article><article><span>Growth</span><b>+${b.growth}%</b></article><article><span>Orders / projects</span><b>${b.orders}</b></article><article><span>Customers</span><b>${b.customers.length}</b></article></div><div class="boundary"><b>Isolation check</b><p>Current request tenantId = <code>${b.id}</code>. Production authorization and PostgreSQL RLS would enforce this boundary server-side.</p></div></div>`;
 else page=`<div class="metrics"><article><span>Revenue</span><b>${money(b.revenue)}</b><small>${b.currency} · current period</small></article><article><span>Orders / projects</span><b>${b.orders}</b><small>processed</small></article><article><span>Customers</span><b>${b.customers.length}</b><small>${b.customers.filter(c=>c.status==='Active').length} active</small></article><article><span>Growth</span><b>+${b.growth}%</b><small>reference period</small></article></div><div class="split"><div class="panel"><label>ACTIVITY</label><h2>What changed</h2><div class="activity">${b.activities.map(a=>`<p><b>${esc(a.message)}</b><span>${a.date}</span></p>`).join('')}</div></div><div class="panel"><label>ASSISTANT</label><h2>Ask this workspace</h2><textarea id="assistantQ" placeholder="How many customers?">${esc(assistant)}</textarea><button id="askAssistant">Ask tenant data</button>${assistant?`<div class="assistant-answer">${esc(ws.assistant(assistant))}</div>`:''}</div></div>`;
 root.innerHTML=`<main><header><strong>MULTI-BUSINESS WORKSPACE</strong><span> / tenant-aware product reference</span><a href="https://github.com/gespitia/multi-business-workspace">Repository ↗</a></header><section class="hero"><div><label>MULTI-TENANT FRONTEND ARCHITECTURE</label><h1>One owner.<br><em>Multiple businesses.</em></h1><p>Switch context, change permissions, write data and trace the request boundary.</p></div><div class="context"><span>ACTIVE TENANT</span><b>${esc(b.name)}</b><small>${esc(b.type)} · ${ws.context.role}</small></div></section><section class="demo-guide panel"><div class="guide-copy"><label>INTERACTIVE PROOF</label><h2>Five actions. Five pieces of evidence.</h2></div><div class="guide-steps">${[['1','Switch business','Data changes'],['2','Change role','Permissions change'],['3','Modify data','Real tenant write'],['4','Ask assistant','Scoped read'],['5','Trace isolation','Live request log']].map(x=>`<button data-demo-step="${x[0]}" class="${demoStep===Number(x[0])?'selected':''}"><b>0${x[0]}</b><span>${x[1]}</span><small>${x[2]}</small></button>`).join('')}</div>${proof()}</section><nav class="mobile-nav">${nav.map(n=>`<button class="${section===n[0]?'active':''}" data-section="${n[0]}">${n[1]}</button>`).join('')}</nav><section class="workspace"><aside><label>WORKSPACE</label>${nav.map(n=>`<button class="${section===n[0]?'active':''}" data-section="${n[0]}">${n[1]}</button>`).join('')}<hr><label>BUSINESSES</label>${ws.all().map(x=>`<button class="${x.id===b.id?'active':''}" data-tenant="${x.id}"><b>${esc(x.name)}</b><small>${esc(x.type)}</small></button>`).join('')}<label class="role-label">ROLE</label><select id="role">${(['owner','manager','viewer'] as Role[]).map(r=>`<option value="${r}" ${ws.context.role===r?'selected':''}>${r}</option>`).join('')}</select></aside><section class="content">${page}</section></section><section class="architecture panel"><label>PRODUCTION BOUNDARY</label><div><span>UI / App Shell</span><i>→</i><span>Tenant Context</span><i>→</i><span>Backend Core</span><i>→</i><span>Tenant Repository</span><i>→</i><span>PostgreSQL / RLS</span></div></section><footer>Browser-first reference implementation. The demo executes tenant-scoped reads/writes locally; server authorization and PostgreSQL RLS are explicitly marked as production boundaries.</footer></main>`;
 root.querySelectorAll('[data-demo-step]').forEach(x=>x.addEventListener('click',()=>{demoStep=Number((x as HTMLElement).dataset.demoStep);if(demoStep===1){ws.switchTo(ws.context.tenantId==='blue-table'?'northline':'blue-table');section='overview';query=''}if(demoStep===2){const r=ws.context.role;ws.setRole(r==='owner'?'manager':r==='manager'?'viewer':'owner');section='overview'}if(demoStep===3){section='customers'}if(demoStep===4){assistant='How many customers does this tenant have?';section='overview'}if(demoStep===5){section='reports'}render()}));
 root.querySelectorAll('[data-section]').forEach(x=>x.addEventListener('click',()=>{section=(x as HTMLElement).dataset.section!;query='';render()}));root.querySelectorAll('[data-tenant]').forEach(x=>x.addEventListener('click',()=>{ws.switchTo((x as HTMLElement).dataset.tenant!);section='overview';query='';render()}));root.querySelector('#role')?.addEventListener('change',e=>{ws.setRole((e.target as HTMLSelectElement).value as Role);render()});root.querySelector('#search')?.addEventListener('input',e=>{query=(e.target as HTMLInputElement).value;render();(root.querySelector('#search') as HTMLInputElement)?.focus()});
 root.querySelector('#addCustomer')?.addEventListener('click',()=>{const n=prompt('Customer name');const e=prompt('Email');if(n&&e){ws.addCustomer(n,e);render()}});root.querySelector('#addItem')?.addEventListener('click',()=>{const n=prompt('Name');const c=prompt('Category');const p=Number(prompt('Price')||0);if(n&&c){ws.addItem(n,c,p);render()}});root.querySelector('#askAssistant')?.addEventListener('click',()=>{assistant=(root.querySelector('#assistantQ') as HTMLTextAreaElement).value;render()});root.querySelector('#proofForm')?.addEventListener('submit',e=>{e.preventDefault();const n=(root.querySelector('#proofName') as HTMLInputElement).value,e2=(root.querySelector('#proofEmail') as HTMLInputElement).value;if(n&&e2){ws.addCustomer(n,e2);render()}});root.querySelector('#proofAskBtn')?.addEventListener('click',()=>{assistant=(root.querySelector('#proofAsk') as HTMLInputElement).value;render()});
}
}

const app=document.querySelector<HTMLElement>('#app');if(app)mount(app);